# Generated by Django 4.2.1 on 2023-06-19 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='oreder_id',
            new_name='order_id',
        ),
    ]
