# Generated by Django 4.2.1 on 2023-07-05 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_subscriber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='name',
        ),
    ]
