# Generated by Django 4.2.1 on 2023-07-12 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='ContactUs',
        ),
    ]
