# Generated by Django 4.2.1 on 2023-07-12 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_rename_contact_contactus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactUs',
            new_name='Contact',
        ),
    ]
